2015/02/14 01:08:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "articulo/agregar".' in C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/agrega...')
#1 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=articulo/agregar
---
2015/02/14 01:08:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "articulo/".' in C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/')
#1 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=articulo/
---
2015/02/14 01:08:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "articulo".' in C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo')
#1 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=articulo
---
2015/02/14 01:10:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "gii".' in C:\xampp\htdocs\topicos\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(270): CController->missingAction('gii')
#1 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('gii')
#2 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/gii')
#3 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=site/gii
---
2015/02/14 01:10:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Gii".' in C:\xampp\htdocs\topicos\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(270): CController->missingAction('Gii')
#1 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('Gii')
#2 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/Gii')
#3 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=site/Gii
---
2015/02/14 01:11:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Gii".' in C:\xampp\htdocs\topicos\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(270): CController->missingAction('Gii')
#1 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('Gii')
#2 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/Gii')
#3 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=site/Gii
---
2015/02/14 01:11:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "gii".' in C:\xampp\htdocs\topicos\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(270): CController->missingAction('gii')
#1 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('gii')
#2 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/gii')
#3 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=site/gii
---
2015/02/16 22:39:56 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'revista'@'localhost' (using password: YES)' in C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\topicos\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\topicos\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\topicos\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8080/topicos/yii/revista/index.php?r=gii
---
2015/02/16 22:58:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'revista'@'localhost' (using password: YES)' in C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\topicos\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\topicos\yii\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\topicos\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost:8080/topicos/yii/revista/index.php?r=gii/form/index
---
2015/02/16 23:14:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'revista'@'localhost' (using password: YES)' in C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\topicos\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\topicos\yii\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\topicos\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost:8080/topicos/yii/revista/index.php?r=gii
---
2015/02/16 23:16:08 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\topicos\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\topicos\yii\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\topicos\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost:8080/topicos/yii/revista/index.php?r=gii
---
2015/02/16 23:16:09 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\topicos\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\topicos\yii\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\topicos\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost:8080/topicos/yii/revista/index.php?r=gii
---
2015/02/16 23:16:10 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\topicos\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\topicos\yii\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\topicos\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost:8080/topicos/yii/revista/index.php?r=gii
---
2015/02/16 23:16:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\topicos\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\topicos\yii\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\topicos\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost:8080/topicos/yii/revista/index.php?r=gii
---
2015/02/16 23:16:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\topicos\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\topicos\yii\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\topicos\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost:8080/topicos/yii/revista/index.php?r=gii
---
2015/02/16 23:16:13 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\topicos\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\topicos\yii\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\topicos\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost:8080/topicos/yii/revista/index.php?r=gii
---
2015/02/16 23:16:15 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\topicos\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\topicos\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\topicos\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\topicos\yii\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\topicos\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\topicos\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\topicos\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\topicos\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\topicos\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\topicos\yii\revista\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/topicos/yii/revista/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost:8080/topicos/yii/revista/index.php?r=gii
---
