2015/02/12 01:33:10 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'contreras'@'localhost' (using password: YES)' in C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\framework\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\framework\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\framework\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\framework\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\framework\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\framework\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=gii/default/index
---
2015/02/12 01:34:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'contreras'@'localhost' (using password: YES)' in C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\framework\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\framework\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\framework\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\framework\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\framework\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\framework\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=gii/default/index
---
2015/02/14 00:33:19 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/create')
#9 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=articulo/create
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=articulo/create
---
2015/02/14 00:33:22 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/create')
#9 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=articulo/create
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=site/login
---
2015/02/14 00:33:32 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/create')
#9 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=articulo/create
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=site/login
---
2015/02/14 00:49:54 [error] [exception.CException] exception 'CException' with message 'Alias "articulo_autor.php" is invalid. Make sure it points to an existing directory or file.' in C:\xampp\htdocs\framework\yii\framework\YiiBase.php:348
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\gii\generators\crud\CrudCode.php(59): YiiBase::import('articulo_autor....', true)
#1 C:\xampp\htdocs\framework\yii\framework\validators\CInlineValidator.php(42): CrudCode->validateModel('model', Array)
#2 C:\xampp\htdocs\framework\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(CrudCode), 'model')
#3 C:\xampp\htdocs\framework\yii\framework\base\CModel.php(159): CValidator->validate(Object(CrudCode), NULL)
#4 C:\xampp\htdocs\framework\yii\framework\gii\CCodeGenerator.php(159): CModel->validate()
#5 C:\xampp\htdocs\framework\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#6 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#7 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('index')
#11 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#12 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=gii/crud/index
---
2015/02/14 01:08:11 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/create')
#9 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=articulo/create
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=articulo
---
2015/02/14 01:08:14 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/create')
#9 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=articulo/create
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=articulo
---
2015/02/14 01:08:15 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/create')
#9 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=articulo/create
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=articulo
---
2015/02/14 01:09:14 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/create')
#9 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=articulo/create
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=articulo
---
2015/02/14 01:09:24 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/create')
#9 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=articulo/create
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=articulo
---
2015/02/14 01:09:26 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/create')
#9 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=articulo/create
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=articulo
---
2015/02/14 01:09:28 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/create')
#9 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=articulo/create
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=articulo
---
2015/02/14 01:09:58 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/create')
#9 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=articulo/create
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=articulo/index
---
2015/02/14 01:10:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "agregar".' in C:\xampp\htdocs\framework\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\CController.php(270): CController->missingAction('agregar')
#1 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('agregar')
#2 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/agrega...')
#3 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=articulo/agregar
---
2015/02/16 18:39:52 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('articulo/create')
#9 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\framework\yii\revista\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/framework/yii/revista/index.php?r=articulo/create
HTTP_REFERER=http://localhost:8080/framework/yii/revista/index.php?r=site/login
---
